"""empty message

Revision ID: 421fe4bf8b2e
Revises: a5cffa318ac2
Create Date: 2024-03-31 00:36:36.412931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '421fe4bf8b2e'
down_revision = 'a5cffa318ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('eyes_color', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('eyes_color'),
    sa.UniqueConstraint('last_name'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('people')
    # ### end Alembic commands ###
